version: '2'
services:
    jhbookz-app:
        image: jhbookz
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhbookz-mysql:3306/jhbookz?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhbookz-mysql:
        extends:
            file: mysql.yml
            service: jhbookz-mysql
